services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: recipe-manager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 10

  recipe-manager:
    build: .
    container_name: recipe-manager-api
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
